site_name: MnMS
site_url: ""
use_directory_urls: false
site_description: 'MnMS ''s documentation'
nav:
    - Home: index.md
    - Installation: installation.md
    - Tutorials:
        - Main: TutorialSeminar.ipynb
        - Graph: TutorialGraph.ipynb
        - Demand and Decision Model: TutorialDemandTravelDecision.ipynb
    - Code Reference:
        - mnms: reference/SUMMARY.md

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/licit-lab/mnms

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py  #
  - mkdocstrings:
      watch:
      - src/mnms  #
  - mkdocs-jupyter:
      include: ["*.ipynb"]
#      execute: true
      include_source: True

